.KEY destination/A

COPY NN01:NEONnoir01 TO RAM:
COPY NN02:NEONnoir02 TO RAM:
COPY NN02:NEONnoir03 TO RAM:
COPY NN02:NEONnoir04 TO RAM:

JOIN RAM:NEONnoir01 RAM:NEONnoir02 RAM:NEONnoir03 RAM:NEONnoir04 AS RAM:NEONnoir.lha
LHA x RAM:NEONnoir.lha <destination>/

DELETE RAM:NEONnoir01
DELETE RAM:NEONnoir02
DELETE RAM:NEONnoir03
DELETE RAM:NEONnoir04
DELETE RAM:NEONnoir.lha
