.KEY destination/A

COPY NN01:NEONnoir01 TO RAM:
COPY NN02:NEONnoir02 TO RAM:

JOIN RAM:NEONnoir01 RAM:NEONnoir02 AS RAM:NEONnoir.lha
LHA x RAM:NEONnoir.lha <destination>/

DELETE RAM:NEONnoir01
DELETE RAM:NEONnoir02
DELETE RAM:NEONnoir.lha
